# Generated by Django 3.0.8 on 2020-08-10 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Peoduct',
            new_name='Product',
        ),
    ]
